artifact_location: file:///D:\amazon_delivery_prediction\models\mlflow_runs/898508248766111594
creation_time: 1758821343555
experiment_id: '898508248766111594'
last_update_time: 1758821343555
lifecycle_stage: active
name: amazon_delivery_prediction
