channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=25.2
- pip:
  - mlflow==2.5.0
  - cloudpickle==2.2.1
  - numpy==1.24.3
  - psutil==7.1.0
  - scikit-learn==1.3.0
  - scipy==1.11.1
name: mlflow-env
